//
//  GraphicalResources.swift
//  SlidingPanelExamples
//
//  Created by Sébastien MICHOY on 4/4/16.
//  Copyright (c) 2016 Sébastien MICHOY. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class GraphicalResources : NSObject {

    //// Cache

    private struct Cache {
        static var imageOfMenuIcon: UIImage?
        static var menuIconTargets: [AnyObject]?
    }

    //// Drawing Methods

    public class func drawMenuIcon() {
        //// Color Declarations
        let menuButtonColor = UIColor(red: 0.123, green: 0.123, blue: 0.123, alpha: 1.000)

        //// Menu Icon Group
        //// Bottom Drawing
        let bottomPath = UIBezierPath(roundedRect: CGRect(x: 0, y: 14.5, width: 22, height: 3.5), cornerRadius: 1.75)
        menuButtonColor.setFill()
        bottomPath.fill()


        //// Middle Drawing
        let middlePath = UIBezierPath(roundedRect: CGRect(x: 0, y: 7.25, width: 22, height: 3.5), cornerRadius: 1.75)
        menuButtonColor.setFill()
        middlePath.fill()


        //// Top Drawing
        let topPath = UIBezierPath(roundedRect: CGRect(x: 0, y: 0, width: 22, height: 3.5), cornerRadius: 1.75)
        menuButtonColor.setFill()
        topPath.fill()
    }

    //// Generated Images

    public class var imageOfMenuIcon: UIImage {
        if Cache.imageOfMenuIcon != nil {
            return Cache.imageOfMenuIcon!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 22, height: 18), false, 0)
            GraphicalResources.drawMenuIcon()

        Cache.imageOfMenuIcon = UIGraphicsGetImageFromCurrentImageContext().imageWithRenderingMode(.AlwaysOriginal)
        UIGraphicsEndImageContext()

        return Cache.imageOfMenuIcon!
    }

    //// Customization Infrastructure

    @IBOutlet var menuIconTargets: [AnyObject]! {
        get { return Cache.menuIconTargets }
        set {
            Cache.menuIconTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector(NSSelectorFromString("setImage:"), withObject: GraphicalResources.imageOfMenuIcon)
            }
        }
    }

}
